# Generated by Django 4.1 on 2022-08-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='type',
            new_name='category',
        ),
    ]
